optimizer: GridSearchCV
validation: 5-fold StratifiedKFold
params:
  C:
    type: float
    choices:
    - 0.01
    - 0.1
    - 1.0
    - 10.0
    - 100.0
    scale: log
  penalty:
    type: categorical
    choices:
    - l1
    - l2
  solver:
    type: categorical
    choices:
    - liblinear
    - saga
