"""initial_schema

Revision ID: bca08d46b4d4
Revises: 
Create Date: 2026-09-06 23:20:47.147219

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bca08d46b4d4'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('mlflow_run_id', sa.String(), nullable=False),
    sa.Column('mlflow_model_name', sa.String(), nullable=False),
    sa.Column('mlflow_model_version', sa.Integer(), nullable=False),
    sa.Column('framework', sa.Enum('SKLEARN', 'XGBOOST', 'PYTORCH', name='modelframeworkenum'), nullable=False),
    sa.Column('model_family', sa.String(), nullable=False),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feature_list', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('dataset_version', sa.String(), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'REGISTERED', 'CHALLENGER', 'CHAMPION', 'ARCHIVED', name='modelstatusenum'), nullable=False),
    sa.Column('is_shadow_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_mlflow_run_id'), 'model_versions', ['mlflow_run_id'], unique=True)
    op.create_table('security_events',
    sa.Column('dedup_hash', sa.String(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('destination_ip', postgresql.INET(), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', 'ICMP', 'OTHER', name='protocolenum'), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('packet_count', sa.Integer(), nullable=False),
    sa.Column('tcp_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset_source', sa.Enum('NSL_KDD', 'CICIDS_2017', 'UNSW_NB15', 'BETH', 'LIVE', name='datasetsourceenum'), nullable=False),
    sa.Column('threat_intel_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_dedup_hash'), 'security_events', ['dedup_hash'], unique=True)
    op.create_index(op.f('ix_security_events_destination_ip'), 'security_events', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_security_events_source_ip'), 'security_events', ['source_ip'], unique=False)
    op.create_index('ix_security_events_threat_intel_null', 'security_events', ['threat_intel_data'], unique=False, postgresql_where=sa.text('threat_intel_data IS NULL'))
    op.create_index(op.f('ix_security_events_timestamp'), 'security_events', ['timestamp'], unique=False)
    op.create_table('predictions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_class', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('class_probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('inference_latency_ms', sa.Float(), nullable=False),
    sa.Column('is_shadow', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['security_events.id'], ),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_event_id'), 'predictions', ['event_id'], unique=False)
    op.create_index(op.f('ix_predictions_is_shadow'), 'predictions', ['is_shadow'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_table('alerts',
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severityenum'), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('source_ip', postgresql.INET(), nullable=False),
    sa.Column('destination_ip', postgresql.INET(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_index(op.f('ix_alerts_acknowledged'), 'alerts', ['acknowledged'], unique=False)
    op.create_index(op.f('ix_alerts_attack_type'), 'alerts', ['attack_type'], unique=False)
    op.create_index(op.f('ix_alerts_dedup_key'), 'alerts', ['dedup_key'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source_ip'), 'alerts', ['source_ip'], unique=False)
    op.create_table('xai_explanations',
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('celery_task_id', sa.String(), nullable=False),
    sa.Column('method', sa.Enum('SHAP', 'LIME', 'ATTENTION', name='xaimethodenum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPUTING', 'COMPLETE', 'FAILED', name='xaistatusenum'), nullable=False),
    sa.Column('feature_contributions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xai_explanations_celery_task_id'), 'xai_explanations', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_xai_explanations_prediction_id'), 'xai_explanations', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xai_explanations_prediction_id'), table_name='xai_explanations')
    op.drop_index(op.f('ix_xai_explanations_celery_task_id'), table_name='xai_explanations')
    op.drop_table('xai_explanations')
    op.drop_index(op.f('ix_alerts_source_ip'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_dedup_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_attack_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_acknowledged'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_is_shadow'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_event_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_security_events_timestamp'), table_name='security_events')
    op.drop_index('ix_security_events_threat_intel_null', table_name='security_events', postgresql_where=sa.text('threat_intel_data IS NULL'))
    op.drop_index(op.f('ix_security_events_source_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_destination_ip'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_dedup_hash'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_model_versions_mlflow_run_id'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
